### ISSUE TITLE
No const functions?

### ISSUE THREAD

**Issue by parisholley** [51Degrees/device-detection-cxx#7]
Note: I don't have a c/c++ background..

I'm working on the Rust wrapper for this project and hitting a potential "performance" wall:

https://github.com/51Degrees/device-detection-cxx/blob/214a7663337e7f6af5a0c9291a6f94ea7919d0b4/src/hash/EngineHash.hpp#L165

and here

https://github.com/51Degrees/common-cxx/blob/4aad033453fb1459bcccd643bffceafa0d5f37ea/ResultsBase.hpp#L212

These methods, which do the heavy lifting of looking up a UA and then access the resulting data, are not marked as const, meaning only one consumer can lookup at a time? I would have thought that the lookup process is in-memory and non-mutating? As it stands, i'd need to to use a Mutex on the rust side to prevent concurrent access.

**Comment by ben51degrees** [comment]
Hi @parisholley ,
The C structues inside the C++ Engine classes already handle concurrent access. So you shouldn't need to use a mutex to access,  unless there is something in the way Rust handles C++ instances that I'm not aware of?

While the method is non-mutating on the class itself, it could be desdcribed as mutating on the C structures it contains. The C structures handle concurrent access, and are not necessarily in memory depending on the configuration. So there will be counter swaps happening, as well as allocations, rather than just looking up in static memory.

I will look into this a bit more to see if this is strictly const considering the C structures. Let me know if there is something I'm missing around the need to use a mutex.

Thanks,
Ben.

**Comment by parisholley** [comment]
Rust prefers you respect the signatures of C (eg: const and mutability), so if it is not marked in const, rust will force you to ensure only one thread/process has an active borrow on that object, which some type of mutex is required. it is possible to hack around it and make all access as "unsafe" in rust land, but from what you described, you've implemented "interior mutability", which is a valid approach (at least in rust land) and considered safe to share. Even in C land, if it is expected that the EngineHash can be access by multiple threads, or via .NET/Java, etc under multiple threads, i'd make the case it should be const.

**Comment by parisholley** [comment]
forgot to note, i've been writing my crate against a fork of common-cxx and this lib (where the methods i touch, are marked as const), and works great across multi-threads and no leaks.

**Comment by ben51degrees** [comment]
Hi @parisholley ,
I see. Don't think I've encountered that with other wrapper languages. I've taken this as an opportunity to mark everything that can be const, as it's safer, and I'm sure there will be other languages out there which work in a similar way to Rust. I suspect it won't be in the next release, as there will be a lot of checks against other wrapper languages that would need to be done to verify the changes. I'll let you know when we plan to make those changes live.

**Comment by parisholley** [comment]
closing as i decided to integrate with c code vs c++, though i'd imagine the same thing would apply in c land as well (though I work around this by using const * in my wrapper code and ignore warnings of passing the ptr down)
