### ISSUE TITLE
Performance Degredation

### ISSUE THREAD

**Issue by ben51degrees** [51Degrees/device-detection-cxx#88]
It seems there is a drop in performance when run on the GitHub Ubuntu runners, which drops off around 26th May.

Here is the CI performance graph leading up to the drop:
![perf-graph-8444972828-0-Ubuntu_x64_Release-DetectionsPerSecond](https://github.com/51Degrees/device-detection-cxx/assets/14220556/9a7089c2-b3b5-48c5-9c7b-457c31092dfc)

And here it is after:
![perf-graph-8531547167-84-Ubuntu_x64_Release-DetectionsPerSecond](https://github.com/51Degrees/device-detection-cxx/assets/14220556/5b8c2c4c-c740-49d7-bbb6-e67aca031285)

The change from mean seems just under the 2 standard deviations allowed by CI. However, the change seems to have been a permanent one.

A couple of ideas on what could have an impact:
- A change in the GitHub runner,
- The introduction of WebView header values into the data file, which could have been around that time.

**Comment by justadreamer** [comment]
The change in performance was tolerated (even though it was below 2sd) due to the fact that we don't fetch more than 1 page of artifacts [here](https://github.com/51Degrees/common-ci/blob/4e6f3b727ea3c5a5006917a1a8327d2054f438c0/steps/compare-performance.ps1#L234) - and sometimes there is just not enough artifacts to do the proper comparison - and then the bootstrapping condition (less than 10) kicks in - which tolerates any result [here](https://github.com/51Degrees/common-ci/blob/4e6f3b727ea3c5a5006917a1a8327d2054f438c0/steps/compare-performance.ps1#L197) - so one of the precautions to implement - is to add fetching 3 pages of artifacts - to be guaranteed to have more than 10 data points for comparison.  @pi-alexander-popel please look into adding pagination to that gh api call.

**Comment by justadreamer** [comment]
The above has been addressed in https://github.com/51Degrees/common-ci/pull/90 - adding more artifact results per page - so we get a longer history - guaranteeing more than 10 historical points.
